name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install backend dependencies
      run: |
        cd server
        npm install
    
    - name: Run backend tests
      run: |
        cd server
        npm test
    
    - name: Test user promotion
      run: |
        cd server
        npm start &
        sleep 5
        
        # تسجيل دخول كقائد
        TOKEN=$(curl -s -X POST http://localhost:5000/api/auth/login \
          -H "Content-Type: application/json" \
          -d '{"username":"egamer","password":"g96n00r0"}' | jq -r '.token')
        
        # إنشاء مستخدم جديد
        curl -X POST http://localhost:5000/api/auth/register \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $TOKEN" \
          -d '{"username":"testuser","email":"test@example.com","password":"password123","passwordConfirm":"password123","discordUsername":"test#1234","fullName":"Test User","birthDate":"2000-01-01"}'
        
        # الحصول على ID المستخدم الجديد
        USER_ID=$(curl -s -X GET http://localhost:5000/api/users \
          -H "Authorization: Bearer $TOKEN" | jq -r '.data.users[0]._id')
        
        # ترقية المستخدم إلى أدمن
        curl -X PATCH http://localhost:5000/api/users/$USER_ID/promote \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $TOKEN" \
          -d '{"newRole":"admin"}' | jq
